# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8505153c5c88be969c61ba80be2959e3d389e9a9a2e8f965fa6f6bb297a1937672d28bc57e12ae70faa94837d0aa1676c385228a62af2e93a412fe80ae4fd4c1

test:
  secret_key_base: f7fa2e880620a42ed64738128fa674c70e3a33388e35e7b60a8e657cf008e95665fdf230958e814f96570eda27ae50bc4e723d3ba4bac84ba2ea9e54b7b9b68d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
